<?php

/**
 * Platform × format catalog — specs from affiliate social content matrix (2026).
 * Each format_key maps to generation rules used by Traffic setup and Content Employee.
 */
return [
    'platforms' => [
        'instagram' => ['label' => 'Instagram', 'icon' => 'mdi:instagram'],
        'tiktok' => ['label' => 'TikTok', 'icon' => 'mdi:tiktok'],
        'youtube' => ['label' => 'YouTube', 'icon' => 'mdi:youtube'],
        'facebook' => ['label' => 'Facebook', 'icon' => 'mdi:facebook'],
        'twitter' => ['label' => 'X (Twitter)', 'icon' => 'mdi:twitter'],
        'threads' => ['label' => 'Threads', 'icon' => 'mdi:threads'],
        'linkedin' => ['label' => 'LinkedIn', 'icon' => 'mdi:linkedin'],
        'reddit' => ['label' => 'Reddit', 'icon' => 'mdi:reddit'],
        'pinterest' => ['label' => 'Pinterest', 'icon' => 'mdi:pinterest'],
    ],

    'intensity_presets' => [
        'starter' => [
            'label' => 'Starter',
            'description' => 'Light weekly volume — 8–12 posts across top platforms.',
            'formats' => [
                'instagram_reel', 'instagram_carousel', 'tiktok_short', 'facebook_reel',
                'x_text_post', 'linkedin_text_post', 'youtube_short', 'pinterest_static_pin',
            ],
        ],
        'growth' => [
            'label' => 'Growth',
            'description' => 'Balanced mix — 15–20 posts/week aligned to algorithm signals.',
            'formats' => 'all',
        ],
        'power' => [
            'label' => 'Power user',
            'description' => 'Maximum reach — daily short-form + full platform coverage.',
            'formats' => 'all',
            'frequency_multiplier' => 1.5,
        ],
    ],

    'formats' => [
        // Instagram
        'instagram_carousel' => [
            'platform' => 'instagram',
            'label' => 'Carousel',
            'content_type' => 'image',
            'generator' => 'carousel',
            'slides_min' => 5,
            'slides_max' => 10,
            'aspect_ratio' => '4:5',
            'size' => '1080x1350',
            'hashtags_min' => 3,
            'hashtags_max' => 5,
            'frequency_per_week' => 2,
            'signals' => ['saves', 'shares', 'swipe-through', 'originality'],
            'automate' => ['carousel_builder', 'hook_scorer', 'save_bait_captions'],
        ],
        'instagram_reel' => [
            'platform' => 'instagram',
            'label' => 'Reel',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [15, 30],
            'aspect_ratio' => '9:16',
            'hashtags_min' => 3,
            'hashtags_max' => 5,
            'frequency_per_week' => 4,
            'signals' => ['watch_time', 'completion', 'dm_shares'],
            'automate' => ['reel_clipper', 'trending_audio'],
        ],
        'instagram_story' => [
            'platform' => 'instagram',
            'label' => 'Story',
            'content_type' => 'image',
            'generator' => 'story',
            'aspect_ratio' => '9:16',
            'frequency_per_week' => 7,
            'signals' => ['daily_retention', 'replies'],
            'automate' => ['story_templates'],
        ],
        'instagram_photo' => [
            'platform' => 'instagram',
            'label' => 'Single photo',
            'content_type' => 'image',
            'generator' => 'image',
            'aspect_ratio' => '4:5',
            'hashtags_min' => 3,
            'hashtags_max' => 5,
            'frequency_per_week' => 2,
            'signals' => ['saves', 'keyword_caption'],
        ],
        'instagram_live' => [
            'platform' => 'instagram',
            'label' => 'Live',
            'content_type' => 'video',
            'generator' => 'live_outline',
            'frequency_per_week' => 1,
            'signals' => ['live_engagement', 'notifications'],
        ],

        // TikTok
        'tiktok_short' => [
            'platform' => 'tiktok',
            'label' => 'Short clip (15–34s)',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [15, 34],
            'aspect_ratio' => '9:16',
            'hashtags_min' => 3,
            'hashtags_max' => 5,
            'frequency_per_week' => 7,
            'signals' => ['completion', 'rewatch', 'search_keywords'],
            'automate' => ['hook_analyzer', 'auto_captions', 'trending_sound'],
        ],
        'tiktok_tutorial' => [
            'platform' => 'tiktok',
            'label' => 'Tutorial',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [30, 60],
            'aspect_ratio' => '9:16',
            'size' => '1080x1920',
            'frequency_per_week' => 3,
            'signals' => ['completion', 'saves'],
        ],
        'tiktok_storytime' => [
            'platform' => 'tiktok',
            'label' => 'Storytime / POV',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [60, 90],
            'aspect_ratio' => '9:16',
            'size' => '1080x1920',
            'frequency_per_week' => 2,
            'signals' => ['completion', 'comments'],
        ],
        'tiktok_photo_mode' => [
            'platform' => 'tiktok',
            'label' => 'Photo Mode (carousel)',
            'content_type' => 'image',
            'generator' => 'carousel',
            'slides_min' => 3,
            'slides_max' => 8,
            'aspect_ratio' => '9:16',
            'size' => '1080x1920',
            'frequency_per_week' => 2,
            'signals' => ['swipe', 'saves'],
        ],

        // YouTube
        'youtube_short' => [
            'platform' => 'youtube',
            'label' => 'Short',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [30, 45],
            'hashtags_min' => 3,
            'hashtags_max' => 3,
            'frequency_per_week' => 4,
            'signals' => ['viewed_vs_swiped', 'replay', 'search'],
            'automate' => ['title_generator', 'thumbnail_hook'],
        ],
        'youtube_longform' => [
            'platform' => 'youtube',
            'label' => 'Long-form video',
            'content_type' => 'video',
            'generator' => 'longform_outline',
            'aspect_ratio' => '16:9',
            'size' => '1920x1080',
            'frequency_per_week' => 1,
            'signals' => ['session_contribution', 'retention', 'ctr'],
            'automate' => ['chapters', 'description_seo'],
        ],

        // Facebook
        'facebook_reel' => [
            'platform' => 'facebook',
            'label' => 'Reel',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [15, 30],
            'aspect_ratio' => '9:16',
            'hashtags_min' => 1,
            'hashtags_max' => 2,
            'frequency_per_week' => 5,
            'signals' => ['meaningful_interactions', 'shares'],
        ],
        'facebook_native_video' => [
            'platform' => 'facebook',
            'label' => 'Native video',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [60, 180],
            'aspect_ratio' => '16:9',
            'size' => '1920x1080',
            'frequency_per_week' => 2,
            'signals' => ['retention', 'comments'],
        ],
        'facebook_group_post' => [
            'platform' => 'facebook',
            'label' => 'Group discussion',
            'content_type' => 'text',
            'generator' => 'text',
            'frequency_per_week' => 3,
            'signals' => ['group_relevance', 'comments'],
        ],
        'facebook_photo_album' => [
            'platform' => 'facebook',
            'label' => 'Photo album',
            'content_type' => 'image',
            'generator' => 'carousel',
            'slides_min' => 3,
            'slides_max' => 10,
            'aspect_ratio' => '1:1',
            'size' => '1080x1080',
            'frequency_per_week' => 1,
        ],
        'facebook_live' => [
            'platform' => 'facebook',
            'label' => 'Live',
            'content_type' => 'video',
            'generator' => 'live_outline',
            'frequency_per_week' => 1,
        ],

        // X (Twitter)
        'x_native_video' => [
            'platform' => 'twitter',
            'label' => 'Native video',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [15, 140],
            'hashtags_min' => 0,
            'hashtags_max' => 2,
            'frequency_per_week' => 3,
            'signals' => ['native_video_boost', 'bookmarks'],
            'automate' => ['link_in_reply'],
        ],
        'x_thread' => [
            'platform' => 'twitter',
            'label' => 'Thread (2 posts)',
            'content_type' => 'text',
            'generator' => 'thread',
            'thread_parts_min' => 2,
            'thread_parts_max' => 2,
            'char_per_part' => 240,
            'hashtags_min' => 0,
            'hashtags_max' => 2,
            'frequency_per_week' => 2,
            'signals' => ['replies', 'bookmarks'],
            'automate' => ['thread_builder', 'link_in_first_reply'],
        ],
        'x_text_post' => [
            'platform' => 'twitter',
            'label' => 'Text post',
            'content_type' => 'text',
            'generator' => 'text',
            'char_ideal' => [71, 100],
            'hashtags_min' => 0,
            'hashtags_max' => 2,
            'frequency_per_week' => 15,
            'signals' => ['replies', 'bookmarks'],
        ],
        'x_article' => [
            'platform' => 'twitter',
            'label' => 'Article (long-form)',
            'content_type' => 'text',
            'generator' => 'longform_text',
            'frequency_per_week' => 1,
        ],

        // Threads
        'threads_conversational' => [
            'platform' => 'threads',
            'label' => 'Conversational post',
            'content_type' => 'text',
            'generator' => 'text',
            'frequency_per_week' => 10,
            'signals' => ['replies', 'recency'],
            'automate' => ['tone_adaptation'],
        ],
        'threads_short_video' => [
            'platform' => 'threads',
            'label' => 'Short video',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [15, 30],
            'aspect_ratio' => '9:16',
            'size' => '1080x1920',
            'frequency_per_week' => 3,
        ],
        'threads_poll' => [
            'platform' => 'threads',
            'label' => 'Poll',
            'content_type' => 'text',
            'generator' => 'poll',
            'frequency_per_week' => 2,
        ],

        // LinkedIn
        'linkedin_pdf_carousel' => [
            'platform' => 'linkedin',
            'label' => 'PDF carousel',
            'content_type' => 'image',
            'generator' => 'carousel',
            'slides_min' => 8,
            'slides_max' => 15,
            'aspect_ratio' => '4:5',
            'hashtags_min' => 0,
            'hashtags_max' => 3,
            'frequency_per_week' => 2,
            'signals' => ['dwell_time', 'saves', 'see_more_clicks'],
            'automate' => ['pdf_carousel_builder', 'link_in_comment'],
        ],
        'linkedin_text_post' => [
            'platform' => 'linkedin',
            'label' => 'Text / story post',
            'content_type' => 'text',
            'generator' => 'text',
            'hook_chars' => 210,
            'hashtags_min' => 0,
            'hashtags_max' => 3,
            'frequency_per_week' => 3,
            'signals' => ['dwell_time', 'comment_depth'],
            'automate' => ['hook_generator', 'no_link_in_body'],
        ],
        'linkedin_native_video' => [
            'platform' => 'linkedin',
            'label' => 'Native video',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'duration_seconds' => [15, 30],
            'aspect_ratio' => '16:9',
            'size' => '1920x1080',
            'frequency_per_week' => 2,
        ],
        'linkedin_poll' => [
            'platform' => 'linkedin',
            'label' => 'Poll',
            'content_type' => 'text',
            'generator' => 'poll',
            'frequency_per_week' => 1,
        ],
        'linkedin_newsletter' => [
            'platform' => 'linkedin',
            'label' => 'Newsletter / article',
            'content_type' => 'text',
            'generator' => 'longform_text',
            'frequency_per_week' => 1,
        ],

        // Reddit
        'reddit_discussion' => [
            'platform' => 'reddit',
            'label' => 'Discussion post',
            'content_type' => 'text',
            'generator' => 'reddit_discussion',
            'title_max_chars' => 300,
            'frequency_per_week' => 2,
            'signals' => ['upvote_velocity', 'comment_depth'],
            'automate' => ['subreddit_rule_check', 'promo_safe'],
        ],
        'reddit_ama' => [
            'platform' => 'reddit',
            'label' => 'AMA',
            'content_type' => 'text',
            'generator' => 'reddit_ama',
            'frequency_per_week' => 0.25,
        ],
        'reddit_native_video' => [
            'platform' => 'reddit',
            'label' => 'Native video / GIF',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'aspect_ratio' => '16:9',
            'size' => '1920x1080',
            'frequency_per_week' => 1,
        ],
        'reddit_image' => [
            'platform' => 'reddit',
            'label' => 'Image post',
            'content_type' => 'image',
            'generator' => 'image',
            'aspect_ratio' => '16:9',
            'size' => '1920x1080',
            'frequency_per_week' => 1,
        ],

        // Pinterest
        'pinterest_static_pin' => [
            'platform' => 'pinterest',
            'label' => 'Static Pin',
            'content_type' => 'image',
            'generator' => 'pin',
            'aspect_ratio' => '2:3',
            'size' => '1000x1500',
            'frequency_per_week' => 4,
            'signals' => ['seo_keywords', 'save_rate'],
            'automate' => ['pin_title_seo', 'board_strategy'],
        ],
        'pinterest_idea_pin' => [
            'platform' => 'pinterest',
            'label' => 'Idea Pin',
            'content_type' => 'image',
            'generator' => 'carousel',
            'slides_min' => 2,
            'slides_max' => 20,
            'aspect_ratio' => '9:16',
            'size' => '1080x1920',
            'frequency_per_week' => 2,
            'signals' => ['dwell_time', 'saves'],
        ],
        'pinterest_infographic' => [
            'platform' => 'pinterest',
            'label' => 'Infographic Pin',
            'content_type' => 'image',
            'generator' => 'carousel',
            'slides_min' => 3,
            'slides_max' => 8,
            'aspect_ratio' => '2:3',
            'size' => '1000x1500',
            'frequency_per_week' => 2,
        ],
        'pinterest_video_pin' => [
            'platform' => 'pinterest',
            'label' => 'Video Pin',
            'content_type' => 'video',
            'generator' => 'reel_script',
            'aspect_ratio' => '9:16',
            'size' => '1080x1920',
            'frequency_per_week' => 2,
        ],
    ],
];
